production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
<<<<<<< HEAD
    #port: 8985
=======
>>>>>>> ab8b8221b50e23b2988c9705acf105f18ab385b4
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
